import type { TradingAgentId, TradingRoleProfile } from '../../types/agent'
import { AGENT_POSITIONS } from './sceneLayout'

function role(profile: TradingRoleProfile): TradingRoleProfile {
  return profile
}

function pos(id: TradingAgentId) {
  const p = AGENT_POSITIONS[id]
  return {
    position: p.home,
    deskPosition: p.home,
    meetingPosition: p.meeting ?? p.debate ?? p.home,
  }
}

/** Static agent layout for the trading floor PixiJS scene. */
export const TRADING_ROLES: readonly TradingRoleProfile[] = [
  role({
    id: 'coordinator',
    name: '任务协调官',
    title: 'Chief Agent',
    team: 'coordinator',
    status: '待命',
    description: '接收用户任务并协调分析流程',
    skills: ['任务分发', '流程编排', '进度监控'],
    color: '#a78bfa',
    zone: 'command_console',
    ...pos('coordinator'),
    avatarType: 'sprite',
    avatarEmoji: '🎯',
    currentAction: 'standby',
  }),
  role({
    id: 'market_analyst',
    name: '行情技术分析师',
    title: 'Market Analyst',
    team: 'analyst',
    status: '待命',
    description: '分析 A 股行情、K线、成交量、MACD、RSI 等技术指标',
    skills: ['行情数据', '技术指标', '趋势分析'],
    color: '#38bdf8',
    zone: 'analyst_row',
    ...pos('market_analyst'),
    avatarType: 'sprite',
    avatarEmoji: '📈',
    currentAction: 'standby',
  }),
  role({
    id: 'fundamentals_analyst',
    name: '基本面分析师',
    title: 'Fundamentals Analyst',
    team: 'analyst',
    status: '待命',
    description: '分析财务报表、估值、盈利能力和现金流',
    skills: ['财报分析', '估值', '现金流'],
    color: '#22c55e',
    zone: 'analyst_row',
    ...pos('fundamentals_analyst'),
    avatarType: 'sprite',
    avatarEmoji: '📊',
    currentAction: 'standby',
  }),
  role({
    id: 'sentiment_analyst',
    name: '舆情情绪分析师',
    title: 'Sentiment Analyst',
    team: 'analyst',
    status: '待命',
    description: '分析市场情绪、投资者关注度、社媒和股吧情绪',
    skills: ['舆情监控', '情绪评分', '社媒分析'],
    color: '#f97316',
    zone: 'analyst_row',
    ...pos('sentiment_analyst'),
    avatarType: 'sprite',
    avatarEmoji: '💬',
    currentAction: 'standby',
  }),
  role({
    id: 'news_policy_analyst',
    name: '新闻政策分析师',
    title: 'News / Policy Analyst',
    team: 'analyst',
    status: '待命',
    description: '分析宏观政策、行业新闻、公司公告和监管事件',
    skills: ['宏观政策', '行业新闻', '公告解读'],
    color: '#06b6d4',
    zone: 'analyst_row',
    ...pos('news_policy_analyst'),
    avatarType: 'sprite',
    avatarEmoji: '📰',
    currentAction: 'standby',
  }),
  role({
    id: 'bullish_researcher',
    name: '多头研究员',
    title: 'Bullish Researcher',
    team: 'researcher',
    status: '待命',
    description: '提出看多逻辑、上涨催化和买入理由',
    skills: ['多头论证', '增长逻辑', '催化剂'],
    color: '#ef4444',
    zone: 'research_room',
    ...pos('bullish_researcher'),
    avatarType: 'sprite',
    avatarEmoji: '🐂',
    currentAction: 'standby',
  }),
  role({
    id: 'bearish_researcher',
    name: '空头研究员',
    title: 'Bearish Researcher',
    team: 'researcher',
    status: '待命',
    description: '提出看空逻辑、风险暴露和下跌理由',
    skills: ['风险识别', '估值压力', '空头论证'],
    color: '#22c55e',
    zone: 'research_room',
    ...pos('bearish_researcher'),
    avatarType: 'sprite',
    avatarEmoji: '🐻',
    currentAction: 'standby',
  }),
  role({
    id: 'research_manager',
    name: '研究经理',
    title: 'Research Manager',
    team: 'researcher',
    status: '待命',
    description: '总结多空辩论并形成投资计划',
    skills: ['辩论总结', '投资计划', '研究协调'],
    color: '#2563eb',
    zone: 'research_room',
    ...pos('research_manager'),
    avatarType: 'sprite',
    avatarEmoji: '🎓',
    currentAction: 'standby',
  }),
  role({
    id: 'trader',
    name: '交易员',
    title: 'Trader',
    team: 'trader',
    status: '待命',
    description: '将投资计划转化为交易提案',
    skills: ['交易提案', '仓位建议', '执行策略'],
    color: '#eab308',
    zone: 'trading_desk',
    ...pos('trader'),
    avatarType: 'sprite',
    avatarEmoji: '⚡',
    currentAction: 'standby',
  }),
  role({
    id: 'aggressive_risk',
    name: '进攻型风控',
    title: 'Aggressive Risk',
    team: 'risk',
    status: '待命',
    description: '从收益机会角度评估风险',
    skills: ['进攻配置', '机会评估', '收益导向'],
    color: '#fb7185',
    zone: 'risk_room',
    ...pos('aggressive_risk'),
    avatarType: 'sprite',
    avatarEmoji: '🔥',
    currentAction: 'standby',
  }),
  role({
    id: 'neutral_risk',
    name: '中性风控',
    title: 'Neutral Risk',
    team: 'risk',
    status: '待命',
    description: '平衡收益、波动、估值和仓位',
    skills: ['风险平衡', '中性评估', '组合约束'],
    color: '#94a3b8',
    zone: 'risk_room',
    ...pos('neutral_risk'),
    avatarType: 'sprite',
    avatarEmoji: '⚖️',
    currentAction: 'standby',
  }),
  role({
    id: 'conservative_risk',
    name: '保守型风控',
    title: 'Conservative Risk',
    team: 'risk',
    status: '待命',
    description: '强调回撤、流动性、政策和黑天鹅风险',
    skills: ['回撤控制', '黑天鹅', '合规审查'],
    color: '#15803d',
    zone: 'risk_room',
    ...pos('conservative_risk'),
    avatarType: 'sprite',
    avatarEmoji: '🛡️',
    currentAction: 'standby',
  }),
  role({
    id: 'portfolio_manager',
    name: '组合经理 PM',
    title: 'Portfolio Manager',
    team: 'pm',
    status: '待命',
    description: '审批交易提案并输出最终组合决策',
    skills: ['最终决策', '仓位审批', '组合管理'],
    color: '#c084fc',
    zone: 'pm_office',
    ...pos('portfolio_manager'),
    avatarType: 'sprite',
    avatarEmoji: '👔',
    currentAction: 'standby',
  }),
] as const

export const TRADING_ROLE_BY_ID = Object.fromEntries(
  TRADING_ROLES.map((r) => [r.id, r]),
) as Record<TradingAgentId, TradingRoleProfile>

/** Map backend agent_id to frontend id (news_analyst -> news_policy_analyst). */
export function normalizeAgentId(id: string | null | undefined): TradingAgentId | null {
  if (!id) return null
  if (id === 'news_analyst') return 'news_policy_analyst'
  if (id in TRADING_ROLE_BY_ID) return id as TradingAgentId
  return null
}

export const ZONE_LABELS: Record<string, string> = {
  command_console: '中央控制台',
  analyst_row: '分析师工位区',
  research_room: '研究辩论室',
  trading_desk: '交易执行台',
  risk_room: '风控会议室',
  pm_office: 'PM 办公室',
}

export { SCENE_WIDTH, SCENE_HEIGHT } from './sceneLayout'
